on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  wakeup:
    name: wakeup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: node scripts/index.mjs 
      env:
        APIFY_KUSONIME: ${{ secrets.APIFY_KUSONIME }}
        APIFY_SAMEHADAKU: ${{ secrets.APIFY_SAMEHADAKU }}